# Generated by Django 3.0.5 on 2020-04-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=255)),
                ('search_query', models.CharField(max_length=255)),
            ],
        ),
    ]
