# Generated by Django 3.0.5 on 2020-04-23 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0002_videosearch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoSearch',
            new_name='YoutubeVideoSearch',
        ),
    ]
