# Generated by Django 3.0.5 on 2020-04-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0003_auto_20200423_1952'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='youtubevideosearch',
            unique_together={('channel_id', 'search_query')},
        ),
    ]
