# Generated by Django 3.0.5 on 2020-04-25 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0004_auto_20200424_1121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YoutubeVideoSearch',
            new_name='YtSearchPattern',
        ),
    ]
