# Generated by Django 3.0.5 on 2020-04-25 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0005_auto_20200425_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='yt_search_patter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gatherer.YtSearchPattern'),
        ),
    ]
