# Generated by Django 3.0.5 on 2020-04-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0006_video_yt_search_patter'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
