# Generated by Django 3.0.5 on 2020-04-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0007_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
