# Generated by Django 3.0.5 on 2020-04-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0008_video_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='link',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
