# Generated by Django 3.0.5 on 2020-04-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0009_auto_20200426_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='yt_search_patter',
        ),
    ]
