# Generated by Django 3.0.5 on 2020-04-28 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0015_ytchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytsearchpattern',
            name='yt_channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gatherer.YtChannel'),
            preserve_default=False,
        ),
    ]
