# Generated by Django 3.0.5 on 2020-04-28 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0017_auto_20200428_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ytsearchpattern',
            old_name='yt_channel',
            new_name='channel',
        ),
        migrations.AlterUniqueTogether(
            name='ytsearchpattern',
            unique_together={('channel', 'search_query')},
        ),
    ]
