# Generated by Django 3.0.5 on 2020-04-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0018_auto_20200428_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytsearchpattern',
            name='duration',
            field=models.CharField(choices=[('any', 'any'), ('long', 'longer than 20 mins'), ('medium', 'between 4 and 20 mins'), ('short', 'less than 4 mins')], default='long', max_length=6),
        ),
        migrations.AddField(
            model_name='ytsearchpattern',
            name='published_after',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='ytsearchpattern',
            name='published_before',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ytsearchpattern',
            name='search_query',
            field=models.CharField(help_text='use the Boolean NOT (-) and OR (|) operators to exclude videos or to find videos that are associated with one of several search terms.', max_length=255),
        ),
    ]
