# Generated by Django 3.0.5 on 2020-04-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0019_auto_20200429_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytsearchpattern',
            name='published_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ytsearchpattern',
            name='published_before',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
