# Generated by Django 3.0.5 on 2020-04-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0020_auto_20200430_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytsearchpattern',
            name='event_type',
            field=models.CharField(choices=[('any', 'any'), ('long', 'longer than 20 mins'), ('medium', 'between 4 and 20 mins'), ('short', 'less than 4 mins')], default='completed', max_length=6),
        ),
    ]
