# Generated by Django 3.0.5 on 2020-04-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0021_ytsearchpattern_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytsearchpattern',
            name='event_type',
            field=models.CharField(choices=[('completed', 'completed broadcasts'), ('live', 'active broadcasts'), ('upcoming', 'upcoming broadcasts')], default='completed', max_length=9),
        ),
    ]
