# Generated by Django 3.0.5 on 2020-04-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0022_auto_20200430_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ytsearchpattern',
            name='event_type',
            field=models.CharField(choices=[('', 'no broadcasts'), ('completed', 'completed broadcasts'), ('live', 'active broadcasts'), ('upcoming', 'upcoming broadcasts')], default='', max_length=9),
        ),
    ]
