# Generated by Django 3.0.5 on 2020-05-02 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0024_auto_20200430_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('video_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gatherer.Video')),
                ('video_id', models.CharField(max_length=255)),
                ('live_broadcast', models.CharField(blank=True, choices=[('', 'no broadcasts'), ('completed', 'completed broadcasts'), ('live', 'active broadcasts'), ('upcoming', 'upcoming broadcasts')], default='', max_length=9)),
                ('channel_id', models.CharField(max_length=255)),
            ],
            bases=('gatherer.video',),
        ),
    ]
