# Generated by Django 3.0.5 on 2020-05-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0025_youtubevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytsearchpattern',
            name='tags',
            field=models.ManyToManyField(blank=True, to='gatherer.Tag'),
        ),
    ]
