# Generated by Django 3.0.5 on 2020-05-03 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0027_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='update',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gatherer.Update'),
            preserve_default=False,
        ),
    ]
