# Generated by Django 3.0.5 on 2020-05-03 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gatherer', '0028_video_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='update',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gatherer.Update'),
        ),
    ]
